Player/02 implementing player
SE-F24-SP4/semesterproject-4 pull request #63
Opened 2024-04-03 10:14 UTC by AleksKors

- Implemented "Player"
  - Added Player movement
  - Added Player aiming
  - Shooting still not implemented

2024-04-03 14:55 UTC, FearfulSnow commented on Player/pom.xml
> +			<scope>compile</scope>
remove this

2024-04-03 14:55 UTC, FearfulSnow commented on Player/src/main/java/com/github/sef24sp4/player/PlayerControl.java
> +			player.getCoordinates().getAngleBetween(gameSettings.getKeys().getMouseCoordinates());
does not set rotation

2024-04-03 14:55 UTC, FearfulSnow commented on Player/src/main/java/com/github/sef24sp4/player/PlayerPlugin.java
> +	private CommonEntity player;
what not the player class

2024-04-03 15:00 UTC, FearfulSnow commented on Player/src/main/java/com/github/sef24sp4/player/PlayerPlugin.java
> +	private CommonEntity player;
why*

2024-04-03 15:15 UTC, MidnightRocket requested changes

2024-04-03 15:15 UTC, MidnightRocket commented on Player/src/main/java/com/github/sef24sp4/player/PlayerControl.java
> +				player.setX(player.getX() - this.diagonalWalkSpeed);
You can extract `player.getX()` and `player.getY()` into variable.

2024-04-03 15:15 UTC, MidnightRocket commented on Player/src/main/java/com/github/sef24sp4/player/PlayerControl.java
> +			}
Should be an if-else chain instead.

2024-04-03 15:15 UTC, MidnightRocket commented on Player/src/main/java/com/github/sef24sp4/player/PlayerControl.java
> +		}
Can use the `gameSettings.isEntityWithinFrame(IEntity entity)` method.

2024-04-03 15:15 UTC, MidnightRocket commented on Player/src/main/java/com/github/sef24sp4/player/PlayerControl.java
> +		for (CommonEntity player : entityManager.getEntitiesByClass(Player.class)) {
Make use of singleton player

2024-04-03 15:15 UTC, MidnightRocket commented on Player/src/main/java/com/github/sef24sp4/player/PlayerPlugin.java
Use some sort of singletone for Player

2024-04-04 14:29 UTC, MidnightRocket commented
Should wait until this https://github.com/SE-F24-SP4/semesterproject-4/issues/68 is merged into main and then integrated into Player.

2024-04-10 07:19 UTC, AleksKors commented on Player/src/main/java/com/github/sef24sp4/player/PlayerControl.java
> +			}
Not sure if I understand the request. Can you elaborate?

2024-04-10 08:55 UTC, FearfulSnow requested changes

2024-04-10 08:55 UTC, FearfulSnow commented on Player/src/main/java/com/github/sef24sp4/player/Player.java
> +	public void setWalkSpeed(double speed) {
should i put negative numbers here

2024-04-10 08:55 UTC, FearfulSnow commented on Player/src/main/java/com/github/sef24sp4/player/Player.java
> +	}
this is not resolved

2024-04-10 08:55 UTC, FearfulSnow commented on Player/src/main/java/com/github/sef24sp4/player/Player.java
> +	}
can take in negative numbers

2024-04-10 09:17 UTC, FearfulSnow requested changes

2024-04-10 09:17 UTC, FearfulSnow commented on Player/src/main/java/com/github/sef24sp4/player/Player.java
> +			if (speed < 0) {
you might need to make this: speed <= 0. if we want the player to stand still.

2024-04-10 09:50 UTC, FearfulSnow approved these changes

2024-04-10 10:09 UTC, MidnightRocket approved these changes

2024-04-10 10:11 UTC, merged