A star ai/common ai interface
SE-F24-SP4/semesterproject-4 pull request #71
Opened 2024-04-05 09:14 UTC by MartinLundDam

**WHAT IS IT?**
- Interface that exposes the pathfinding method that has its functionality in the AStarAI module. 
- The pom.xml file have been modified with dependencies. 
- The module.info.java file have got a require and exports. 

**MISSING:** 
- The method {calculateNextMove} still needs to be overwritten in the AStarAI module in order to function.

2024-04-05 09:45 UTC, MidnightRocket requested changes

2024-04-05 09:45 UTC, MidnightRocket commented on CommonAI/src/main/java/com/github/sef24sp4/common/ai/IPathfindingProvider.java
> +	 *
Missing a General description of what the method does.

2024-04-05 11:20 UTC, FearfulSnow requested changes

2024-04-05 11:20 UTC, FearfulSnow commented on CommonAI/src/main/java/com/github/sef24sp4/common/ai/IPathfindingProvider.java
> +	 * When the best route towards a target is known. The Entity will navigate to the next step on this route, which is the TargatCoordinate.
The text should not have any info regarting the inner workings of the specific AI, if ALL AI's use nodes and fCost, then i am wrong. 
rewrite: Get the next coordinate of a valid path between entity and target coordinate

2024-04-05 11:20 UTC, FearfulSnow commented on CommonAI/src/main/java/com/github/sef24sp4/common/ai/IPathfindingProvider.java
> +	public IVector calculateNextMove(IEntity entity, IVector targetCoordinate);
Possible name changes:
nextCoordinateInPath()
getFirstCoordinateInPath()

2024-04-10 08:19 UTC, FearfulSnow approved these changes
good ready to be merged

2024-04-10 08:21 UTC, MidnightRocket approved these changes

2024-04-10 08:27 UTC, FearfulSnow approved these changes

2024-04-10 10:24 UTC, MidnightRocket approved these changes

2024-04-10 10:30 UTC, merged