Polygon enemy/11 enemy ai
SE-F24-SP4/semesterproject-4 pull request #93
Opened 2024-04-13 16:03 UTC by FearfulSnow

# Changes
- Polygon enemy have a speed attribute that gets assigned when initilized. This attribute becomes smaller, the higher the edge provided. 

- Polygon enemy can now move towards the players coordinates using its speed attribute, regardless of a pathfindingProvider. 
but if a pathfindingProvider is provided the polygon enemy will move towards the coordinates provided by the pathfindingProvider.

>[!warning]
>Made export on player, to get coordinates.

# Related Issue
#11

2024-04-16 21:06 UTC, MidnightRocket requested changes
There are still some unresolved issues from previous review. 
I also think it is good to wait until #94 is merged.

2024-04-16 21:06 UTC, MidnightRocket commented on PolygonEnemy/src/main/java/com/github/sef24sp4/polygonenemy/PolygonEnemyControlSystem.java
> +				polygonEnemy.setY(polygonEnemy.getY() + movementVector.getY());
Can optimize this code if we wait on #94

2024-04-17 10:24 UTC, FearfulSnow commented on Player/src/main/java/module-info.java
yeah just forgot you could do that ;)

2024-04-18 05:13 UTC, FearfulSnow commented
@MidnightRocket can you look closer at the casting i am doing, because the functions return an IVector and the methods i want to use lies on basicVector, just want to make sure its not the wrong way.

2024-04-18 06:08 UTC, MidnightRocket commented
> @MidnightRocket can you look closer at the casting i am doing, because the functions return an IVector and the methods i want to use lies on basicVector, just want to make sure its not the wrong way.

Luckily I had the foresight that this problem would arise. So I have made the static factory method [`BasicVector.from()`](https://github.com/SE-F24-SP4/semesterproject-4/blob/f3fb7e53d2d86b9db1a036ae994d26055d0cd4c2/Common/src/main/java/com/github/sef24sp4/common/vector/BasicVector.java#L28)

2024-04-19 10:55 UTC, MidnightRocket approved these changes

2024-04-19 11:01 UTC, merged